### ISSUE TITLE
Question: Any way to export the colors to kitty terminal?

### ISSUE THREAD

**Issue by vihu** [rafikdraoui/couleurs.vim#1]
Hello, thank you for your work on this colorscheme, I also really like it! I was wondering if you had a way to generate [kitty](https://sw.kovidgoyal.net/kitty/) terminal theme from the color palette here.

**Comment by rafikdraoui** [comment]
The palette is the same as Gruvbox, using the "hard contrast" variant. You could start with the "Gruvbox Dark" or "Gruvbox Material Dark Hard" themes from `kitty +kitten themes`, and tweak as needed.

This is what I have in my `kitty.conf` for the dark theme:

```
background #1d2021
foreground #ebdbb2
color0 #282828
color1 #cc241d
color2 #98971a
color3 #d79921
color4 #458588
color5 #b16286
color6 #689d6a
color7 #a89984
color8 #928374
color9 #fb4934
color10 #b8bb26
color11 #fabd2f
color12 #83a598
color13 #d3869b
color14 #8ec07c
color15 #ebdbb2

active_border_color #458588
```

If you want the light theme, you can get the color hex codes from `templates/palette.yaml`. If you want to switch back-and-forth between dark and light, you might be able to get something working with https://sw.kovidgoyal.net/kitty/kittens/themes/#command-line-interface.

**Comment by vihu** [comment]
Ah perfect, thank you for answering.
